### ISSUE TITLE
【gcp】 how to skip creating project,but just use existed project

### ISSUE THREAD

**Issue by symsimmy** [hashicorp/nomad-autoscaler-demos#42]
i want use already exists project but not create a new project.so i make some update.
https://github.com/hashicorp/nomad-autoscaler-demos/compare/main...symsimmy:nomad-autoscaler-demos:main
then,it has some error occured.

![image](https://user-images.githubusercontent.com/10104473/185101197-2bf333a7-d58a-4092-9aa1-3c6592879835.png)

can u help me fix this issue,how to use existed project rather than create new one?thx very much

**Comment by lgfa29** [comment]
Hi @symsimmy 👋 

Apologies for the delay here, this repo went out of our radar so we missed notifications.

You can comment out this part of the Terraform configuration that creates the project:
https://github.com/hashicorp/nomad-autoscaler-demos/blob/main/cloud/gcp/terraform/control/main.tf#L43-L48

And then set this line to the project ID you want to use:
https://github.com/hashicorp/nomad-autoscaler-demos/blob/main/cloud/gcp/terraform/control/main.tf#L30

Hope this helps, but feel free to reach out if you are still having problems 🙂
